FROM python:3.10-slim

# Set environment variables
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update && \
    apt-get install -y graphviz
# Set the working directory in the container
WORKDIR /app

COPY . ./

# Install dependencies
RUN pip install -r requirements.txt
