_target_: whydra.algorithms.wrappers.StandaloneFCIPlusStableParallelCached
alpha: 0.05
indep_test: fisherz
use_ci_cache: true
n_jobs: 2
skeleton_backend: auto
augment_backend: auto
dsep_backend: auto
process_min_vars: 150
