loader:
  _target_: whydra.data.BnLearnLoader
  data_dir: "./whydra_benchmarks/cases/bnlearn/{name}/input/{name}.txt"
  ground_truth_dir: "./whydra_benchmarks/cases/bnlearn/{name}/ground.truth/{name}.graph.txt"

# тест хи-квадрат, так как данные дискретные
indep_test: chisq

names:
#  - alarm
  - child
#  - insurance
#  - water