loader:
  _target_: whydra.data.LucasLoader
  data_dir: "./datasets/benchmarks/lucas/data/{name}/{name}_train.data"
  targets_dir: "./datasets/benchmarks/lucas/data/{name}/{name}_train.targets"
  ground_truth_dir: "./datasets/benchmarks/lucas/ground.truth/{name}/{name}.ground.truth.graph.txt"

indep_test: chisq
names:
  - lucas0